webpack 默认配置

{ entry: 'index.js',
  debug: false,
  devtool: false,
  cache: true,
  context: '/Users/liqingliu/Study/sourceAnalysis/webpack/study',
‌  target: 'web',
  module:
   { unknownContextRequest: '.',
     unknownContextRegExp: false,
     unknownContextRecursive: true,
     unknownContextCritical: true,
     exprContextRequest: '.',
     exprContextRegExp: false,
     exprContextRecursive: true,
     exprContextCritical: true,
     wrappedContextRegExp: /.*/,
     wrappedContextRecursive: true,
     wrappedContextCritical: false },
  output: 
   { filename: '[name].js',
     chunkFilename: '[id].js',
     library: '',
     hotUpdateFunction: 'webpackHotUpdate',
     jsonpFunction: 'webpackJsonp',
     libraryTarget: 'var',
     path: '/Users/liqingliu/Study/sourceAnalysis/webpack/study',
     sourceMapFilename: '[file].map[query]',
     hotUpdateChunkFilename: '[id].[hash].hot-update.js',
     hotUpdateMainFilename: '[hash].hot-update.json',
     crossOriginLoading: false,
     hashFunction: 'md5',
     hashDigest: 'hex',
     hashDigestLength: 20,
     sourcePrefix: '\t',
     devtoolLineToLine: false },
  node: 
   { console: false,
     process: true,
     global: true,
     Buffer: true,
     setImmediate: true,
     __filename: 'mock',
     __dirname: 'mock' },
  resolve: 
   { unsafeCache: true,
     modules: [ 'node_modules' ],
     extensions: [ '.js', '.json' ],
     aliasFields: [ 'browser' ],
     mainFields: [ 'browser', 'web', 'browserify', 'main' ] },
  resolveLoader: 
   { unsafeCache: true,
     mainFields: [ 'loader', 'main' ],
     extensions: [ '.js', '.json' ],
     moduleExtensions: [ '-loader' ] } }